[2025-01-05T09:29:10.811+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T09:29:09.641806+00:00 [queued]>
[2025-01-05T09:29:10.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T09:29:09.641806+00:00 [queued]>
[2025-01-05T09:29:10.821+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-01-05T09:29:10.831+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-01-05 09:29:09.641806+00:00
[2025-01-05T09:29:10.838+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2025-01-05T09:29:10.840+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_dag', 'submit_spark_job', 'manual__2025-01-05T09:29:09.641806+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/teams_kafka_to_spark.py', '--cfg-path', '/tmp/tmpr3rlvtn8']
[2025-01-05T09:29:10.842+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask submit_spark_job
[2025-01-05T09:29:10.878+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T09:29:09.641806+00:00 [running]> on host ac3c4f4a38b5
[2025-01-05T09:29:11.164+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_dag' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T09:29:09.641806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T09:29:09.641806+00:00'
[2025-01-05T09:29:11.170+0000] {spark_submit.py:218} INFO - Could not load connection string my_spark_conn, defaulting to yarn
[2025-01-05T09:29:11.171+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 --executor-memory 2G --driver-memory 1G --name SparkKafkaToPostgres --verbose /usr/local/***/include/scripts/kafka_to_postgres_teams.py
[2025-01-05T09:29:11.182+0000] {spark_submit.py:490} INFO - /home/***/.local/bin/spark-submit: line 27: /opt/spark-3.2.0-bin-hadoop3.2/bin/spark-class: No such file or directory
[2025-01-05T09:29:11.192+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 --executor-memory 2G --driver-memory 1G --name SparkKafkaToPostgres --verbose /usr/local/***/include/scripts/kafka_to_postgres_teams.py. Error code is: 127.
[2025-01-05T09:29:11.196+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_kafka_to_postgres_dag, task_id=submit_spark_job, execution_date=20250105T092909, start_date=20250105T092910, end_date=20250105T092911
[2025-01-05T09:29:11.205+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 14 for task submit_spark_job (Cannot execute: spark-submit --master yarn --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 --executor-memory 2G --driver-memory 1G --name SparkKafkaToPostgres --verbose /usr/local/***/include/scripts/kafka_to_postgres_teams.py. Error code is: 127.; 67)
[2025-01-05T09:29:11.229+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-05T09:29:11.246+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
